name: Build on push
on: [push]
jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout v2 branch
        uses: actions/checkout@v2.3.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install & Build
      - run: |
          npm install
          npm run build --if-present
          rm -rf ./docs
          mv ./public ./docs
      - name: Checkout gh-pages branch
      - run: git checkout action_test
      - run: ls -al
      - name: Add & Commit
        uses: EndBug/add-and-commit@v4.4.0
        with:
          add: 'docs'
          message: "Updated: `date +'%Y-%m-%d %H:%M:%S'`"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git log
      - run: ls -al
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "action_test"
          force: true