name: Build on push
on: [push]
jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Echo the greeting's time
        run: echo 'The time was Dell.'