name: Build on push
on:
  push:
    branches:
      - v2
jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [ 15.x ]

    steps:
      - name: Checkout v2 branch
        uses: actions/checkout@v2.3.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm cache
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Gatsby Cache Folder
        uses: actions/cache@v2
        id: gatsby-cache-folder
        with:
          path: .cache
          key: ${{ runner.os }}-cache-gatsby-2
          restore-keys: |
            ${{ runner.os }}-cache-gatsby-2
      - name: Gatsby Public Folder
        uses: actions/cache@v2
        id: gatsby-public-folder
        with:
          path: public/
          key: ${{ runner.os }}-public-gatsby-2
          restore-keys: |
            ${{ runner.os }}-public-gatsby-2
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Build
        run: npx gatsby build
        env:
          NODE_ENV: production
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2.3.2
        with:
          ref: "gh-pages"
          clean: false
      - name: Copy Directories
        run: |
          rm -rf ./docs
          cp -R ./public ./docs
      - name: Add & Commit
        uses: EndBug/add-and-commit@v4.4.0
        with:
          add: 'docs'
          ref: "gh-pages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "gh-pages"
          force: true
