name: Build on push
on: [push]
jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - run: npm run clean
      - run: npm run build
      - run: rm -rf ./docs
      - run: mv ./public ./docs
      - name: Checkout
        uses: actions/checkout@v2.3.2
        with:
          repository: "action_test"
      - name: Add & Commit
        uses: EndBug/add-and-commit@v4.4.0
        
